### PR TITLE
Added support for high DPI.

### PR DESCRIPTION
**Pull request by pvginkel**
xvfb-run allows the DPI to be set through the server args option. A new environment variable SCREEN_DPI has been added to allow this setting to be changed. It defaults to 96, the current default of xvfb-run. Setting it to e.g. 192 will double the resolution of all images generated.

### CODE REVIEW

**Comment by pvginkel** [comment]
I've tested this, and I have verified that the DPI setting is passed correctly into the `xvfb-run` command, but the resolution of the images aren't increased. On Windows this does work. If I run my desktop at 200% scaling, the scale of the images in the HTML report are doubled also. @WoozyMasta could you have a look and see if I'm missing something obvious? I have no experience with the Linux version of Archi. Maybe you can help out?

**Comment by pvginkel** [comment]
I misunderstood what caused the DPI of the exported images to be increased. There's a setting for this. I'm unsure how this can be configured and I'll dive into this.

**Comment by WoozyMasta** [comment]
> I misunderstood what caused the DPI of the exported images to be increased. There's a setting for this. I'm unsure how this can be configured and I'll dive into this.

I didn’t go into detail, but perhaps in addition to DPI you should also specify the screen resolution?

https://github.com/archimatetool/archi/issues/651
https://github.com/archimatetool/archi/issues/596

I quickly found this information, but it didn’t make it any easier

**Comment by pvginkel** [comment]
Thank you for getting back to me. My work was based on the same material, but I went down the wrong road. It took me some time to realize that the resolution of the exported images wasn't determined by the dpi of the machine, but by a setting. There's no need for changes to the docker image to support this.

I created this suggestion for the documentation instead:

https://github.com/WoozyMasta/archimate-ci-image/pull/16

I was successful in increasing the resolution of the exported images with this.

**Pull request closed without merging**
